### ISSUE TITLE
Deduplication Feature

### ISSUE THREAD

**Issue by cmueller-tp** [ph0llux/zff#3]
Hi,

thanks for this project, looks really interesting! About time there is an open source solution for forensic images :)

As it is a really relevant use case for us we'd like to see a forensics file format that supports a deduplication layer. Especially when acquiring multiple systems it would save a great deal of storage.

As we're willing to contribute this feature - or parts - to ZFF  it would be good to hear your thoughts on it to coordinate implementation if you're interested.

Cheers

**Comment by ph0llux** [comment]
Implemented (see current master branch) and will be released with the new Zffv3 format.
